<?php

    $DBserver = "<USE EITHER 127.0.0.1 OR LOCALHOST, KEEP THE QUOTES>";
    $DBuser = "<INSERT YOUR DB USERNAME HERE, KEEP THE QUOTES>";
    $DBpass = "<INSERT YOUR DB PASSWORD HERE, KEEP THE QUOTES>";
    $DBname = "<INSERT YOUR DATABASE NAME HERE, KEEP THE QUOTES>";
    $GAMpath = "<TYPE THE FULL PATH TO GAM EXECUTABLE, KEEP THE QUOTES>";

?>
